version: '3'

services:
    app:
        container_name: locations_ms_app
        restart: always
        build: .
        ports: 
            - "3000:3000"
        links:
            - postgres
        environment: 
            - DB_LOCATIONS_MS_USER="homestead"
            - DB_LOCATIONS_MS_PASSWORD="secret"
            - DB_LOCATIONS_MS_HOST="localhost"
            - DB_LOCATIONS_MS_PORT="5432"
        
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=locations_ms
            - POSTGRES_USER=homestead
            - POSTGRES_PASSWORD=secret
        ports: 
            - '5432:5432'

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        build: .
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181